/** Approved B7 node registry mirrored by the authoritative backend registry. */
import type { NodeTypeSpec, PipelineNodeKind, SchemaColumn } from '@/shared/types/pipeline'

const IN = [{ id: 'in', label: 'Input' }]
const OUT = [{ id: 'out', label: 'Output' }]
const spec = (value: NodeTypeSpec) => value
const field = (key: string, label: string, required = true) => ({ key, label, type: 'text' as const, required })

export const NODE_TYPES: Record<PipelineNodeKind, NodeTypeSpec> = {
  'source-dataset': spec({
    kind: 'source-dataset',
    label: 'Dataset',
    category: 'source',
    icon: 'dataset',
    description: 'Read a tenant-owned catalog dataset.',
    docs: 'Select a governed dataset, discover a database object, or register an uploaded CSV. Credentials are resolved from the vault by the worker.',
    inputs: [],
    outputs: OUT,
    config: [],
  }),
  'select-columns': spec({
    kind: 'select-columns',
    label: 'Select Columns',
    category: 'transform',
    icon: 'columns',
    description: 'Keep approved columns.',
    docs: 'Column selection is evaluated by the worker.',
    inputs: IN,
    outputs: OUT,
    config: [{ key: 'columns', label: 'Columns', type: 'columns', required: true }],
  }),
  'rename-columns': spec({
    kind: 'rename-columns',
    label: 'Rename Columns',
    category: 'transform',
    icon: 'edit',
    description: 'Rename fields.',
    docs: 'Map current names to output names.',
    inputs: IN,
    outputs: OUT,
    config: [{ key: 'renames', label: 'Rename map', type: 'keyvalue', required: true }],
  }),
  filter: spec({
    kind: 'filter',
    label: 'Filter',
    category: 'transform',
    icon: 'filter',
    description: 'Filter rows with the safe formula language.',
    docs: 'Only allowlisted operators, functions, literals, and [field] references are accepted.',
    inputs: IN,
    outputs: OUT,
    config: [{ key: 'formula', label: 'Condition', type: 'formula', required: true }],
  }),
  sort: spec({
    kind: 'sort',
    label: 'Sort',
    category: 'transform',
    icon: 'sort',
    description: 'Sort rows by configured fields.',
    docs: 'Sorting is bounded by the run row limit.',
    inputs: IN,
    outputs: OUT,
    config: [
      {
        key: 'fields',
        label: 'Field directions',
        type: 'keyvalue',
        required: true,
        help: 'Field name to asc or desc.',
      },
    ],
  }),
  join: spec({
    kind: 'join',
    label: 'Join',
    category: 'transform',
    icon: 'join',
    description: 'Join two inputs on approved fields.',
    docs: 'Exactly two incoming edges are required.',
    inputs: [
      { id: 'left', label: 'Left' },
      { id: 'right', label: 'Right' },
    ],
    outputs: OUT,
    config: [
      field('left_field', 'Left field'),
      field('right_field', 'Right field'),
      {
        key: 'join_type',
        label: 'Join type',
        type: 'select',
        required: true,
        defaultValue: 'inner',
        options: [
          { value: 'inner', label: 'Inner' },
          { value: 'left', label: 'Left' },
          { value: 'full', label: 'Full' },
        ],
      },
    ],
  }),
  union: spec({
    kind: 'union',
    label: 'Union',
    category: 'transform',
    icon: 'merge',
    description: 'Combine compatible inputs.',
    docs: 'Two or more incoming edges are required.',
    inputs: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B' },
    ],
    outputs: OUT,
    config: [{ key: 'distinct', label: 'Remove duplicates', type: 'boolean', defaultValue: false }],
  }),
  aggregate: spec({
    kind: 'aggregate',
    label: 'Aggregate',
    category: 'transform',
    icon: 'aggregate',
    description: 'Group and aggregate bounded rows.',
    docs: 'Supported operations are count, sum, minimum, maximum, and average.',
    inputs: IN,
    outputs: OUT,
    config: [
      { key: 'group_by', label: 'Group fields', type: 'columns' },
      { key: 'aggregations', label: 'Validated aggregation definitions', type: 'textarea', required: true },
    ],
  }),
  formula: spec({
    kind: 'formula',
    label: 'Formula',
    category: 'transform',
    icon: 'formula',
    description: 'Create a field using the safe formula language.',
    docs: 'No eval, Python, JavaScript, SQL, or shell execution is available.',
    inputs: IN,
    outputs: OUT,
    config: [field('field', 'Output field'), { key: 'formula', label: 'Formula', type: 'formula', required: true }],
  }),
  'row-validation': spec({
    kind: 'row-validation',
    label: 'Row Validation',
    category: 'transform',
    icon: 'quality',
    description: 'Reject rows that fail approved formula rules.',
    docs: 'Each rule is a JSON object with formula and reason fields. Rejected rows are retained in a protected artifact.',
    inputs: IN,
    outputs: OUT,
    config: [
      {
        key: 'rules',
        label: 'Validation rules',
        type: 'textarea',
        required: true,
        help: 'JSON array of { "formula": "...", "reason": "..." } rules.',
      },
    ],
  }),
  'type-convert': spec({
    kind: 'type-convert',
    label: 'Type Convert',
    category: 'transform',
    icon: 'type',
    description: 'Convert a field to an approved primitive type.',
    docs: 'Conversions fail safely for incompatible values.',
    inputs: IN,
    outputs: OUT,
    config: [
      field('field', 'Field'),
      {
        key: 'target_type',
        label: 'Target type',
        type: 'select',
        required: true,
        options: [
          { value: 'string', label: 'String' },
          { value: 'integer', label: 'Integer' },
          { value: 'number', label: 'Number' },
          { value: 'boolean', label: 'Boolean' },
        ],
      },
    ],
  }),
  deduplicate: spec({
    kind: 'deduplicate',
    label: 'Deduplicate',
    category: 'transform',
    icon: 'deduplicate',
    description: 'Remove duplicate rows.',
    docs: 'Uniqueness is defined by selected fields.',
    inputs: IN,
    outputs: OUT,
    config: [{ key: 'fields', label: 'Key fields', type: 'columns', required: true }],
  }),
  'null-handling': spec({
    kind: 'null-handling',
    label: 'Null Handling',
    category: 'transform',
    icon: 'quality',
    description: 'Drop or replace null values.',
    docs: 'Null handling is deterministic.',
    inputs: IN,
    outputs: OUT,
    config: [
      field('field', 'Field'),
      {
        key: 'strategy',
        label: 'Strategy',
        type: 'select',
        required: true,
        options: [
          { value: 'drop', label: 'Drop rows' },
          { value: 'replace', label: 'Replace value' },
        ],
      },
      { ...field('value', 'Replacement', false), visibleWhen: { key: 'strategy', equals: 'replace' } },
    ],
  }),
  'output-dataset': spec({
    kind: 'output-dataset',
    label: 'Dataset Output',
    category: 'output',
    icon: 'dataset',
    description: 'Write an approved writable dataset.',
    docs: 'The target must be tenant-owned and marked writable in B5.',
    inputs: IN,
    outputs: [],
    config: [
      field('dataset_id', 'Target dataset ID'),
      {
        key: 'write_mode',
        label: 'Write mode',
        type: 'select',
        required: true,
        defaultValue: 'append',
        options: [
          { value: 'append', label: 'Append' },
          { value: 'replace', label: 'Replace' },
        ],
      },
    ],
  }),
  'file-export': spec({
    kind: 'file-export',
    label: 'Protected File',
    category: 'output',
    icon: 'download',
    description: 'Create a protected result artifact.',
    docs: 'Artifacts use tenant-bound keys and temporary signed downloads.',
    inputs: IN,
    outputs: [],
    config: [
      field('filename', 'Label', false),
      {
        key: 'format',
        label: 'Format',
        type: 'select',
        required: true,
        defaultValue: 'csv',
        options: [
          { value: 'csv', label: 'CSV' },
          { value: 'json', label: 'JSON' },
        ],
      },
    ],
  }),
}

export const PALETTE_GROUPS: { label: string; kinds: PipelineNodeKind[] }[] = [
  { label: 'Sources', kinds: ['source-dataset'] },
  {
    label: 'Prepare',
    kinds: [
      'select-columns',
      'rename-columns',
      'filter',
      'sort',
      'deduplicate',
      'null-handling',
      'row-validation',
      'type-convert',
    ],
  },
  { label: 'Combine', kinds: ['join', 'union'] },
  { label: 'Transform', kinds: ['aggregate', 'formula'] },
  { label: 'Outputs', kinds: ['output-dataset', 'file-export'] },
]

export function mockOutputSchema(_kind: PipelineNodeKind): SchemaColumn[] {
  return []
}
