"""roles permissions and governance

Revision ID: 53957b92b086
Revises: 20260721_0003
Create Date: 2026-07-21 14:30:59.405601
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import NAMESPACE_URL, uuid5

import sqlalchemy as sa
from alembic import op

from vip_api.governance.policies import (
    ENTITLEMENT_DEFINITIONS,
    FEATURE_DEFINITIONS,
    QUOTA_DEFINITIONS,
    SYSTEM_PERMISSIONS,
    SYSTEM_ROLE_PERMISSIONS,
    SYSTEM_ROLES,
)

revision: str = "53957b92b086"
down_revision: str | None = "20260721_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _id(kind: str, key: str):
    return uuid5(NAMESPACE_URL, f"vip:{kind}:{key}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlements")),
        sa.UniqueConstraint("key", name=op.f("uq_entitlements_key")),
    )
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("default_enabled", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("key", name=op.f("uq_feature_flags_key")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("key", name=op.f("uq_permissions_key")),
    )
    op.create_table(
        "quota_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("is_hard_limit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_definitions")),
        sa.UniqueConstraint("key", name=op.f("uq_quota_definitions_key")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_assignable", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("key", name=op.f("uq_roles_key")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_role_permission"),
    )
    op.create_table(
        "organization_entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entitlement_id"],
            ["entitlements.id"],
            name=op.f("fk_organization_entitlements_entitlement_id_entitlements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_entitlements_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_entitlements")),
        sa.UniqueConstraint(
            "organization_id", "entitlement_id", name="uq_org_entitlements_org_entitlement"
        ),
    )
    op.create_index(
        "ix_org_entitlements_ends_at", "organization_entitlements", ["ends_at"], unique=False
    )
    op.create_index(
        "ix_org_entitlements_org_status",
        "organization_entitlements",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "organization_quotas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("quota_id", sa.Uuid(), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_quotas_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quota_id"],
            ["quota_definitions.id"],
            name=op.f("fk_organization_quotas_quota_id_quota_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_quotas")),
        sa.UniqueConstraint("organization_id", "quota_id", name="uq_org_quotas_org_quota"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_actor", "audit_events", ["actor_user_id"], unique=False)
    op.create_index(
        "ix_audit_events_org_occurred",
        "audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_type_outcome", "audit_events", ["event_type", "outcome"], unique=False
    )
    op.create_index(
        "ix_audit_events_workspace_occurred",
        "audit_events",
        ["workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "feature_flag_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature_flag_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_flag_id"],
            ["feature_flags.id"],
            name=op.f("fk_feature_flag_overrides_feature_flag_id_feature_flags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_feature_flag_overrides_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_feature_flag_overrides_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flag_overrides")),
        sa.UniqueConstraint(
            "feature_flag_id", "organization_id", "workspace_id", name="uq_feature_overrides_scope"
        ),
    )
    op.create_index(
        "ix_feature_overrides_tenant",
        "feature_flag_overrides",
        ["organization_id", "workspace_id"],
        unique=False,
    )
    op.create_table(
        "quota_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("quota_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_value", sa.BigInteger(), nullable=False),
        sa.Column("reserved_value", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "used_value >= 0 AND reserved_value >= 0",
            name=op.f("ck_quota_usage_quota_usage_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quota_usage_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quota_id"],
            ["quota_definitions.id"],
            name=op.f("fk_quota_usage_quota_id_quota_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_quota_usage_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quota_usage")),
        sa.UniqueConstraint(
            "organization_id",
            "workspace_id",
            "quota_id",
            "period_start",
            name="uq_quota_usage_scope_period",
        ),
    )
    op.create_index(
        "ix_quota_usage_tenant",
        "quota_usage",
        ["organization_id", "workspace_id", "quota_id"],
        unique=False,
    )
    now = datetime.now(UTC)
    bind = op.get_bind()
    bind.execute(
        sa.insert(
            sa.table(
                "permissions",
                sa.column("id"),
                sa.column("key"),
                sa.column("name"),
                sa.column("description"),
                sa.column("scope"),
                sa.column("category"),
                sa.column("is_system"),
                sa.column("created_at"),
                sa.column("updated_at"),
            )
        ),
        [
            {
                "id": _id("permission", item.key),
                "key": item.key,
                "name": item.name,
                "description": "",
                "scope": item.scope.value,
                "category": item.category,
                "is_system": True,
                "created_at": now,
                "updated_at": now,
            }
            for item in SYSTEM_PERMISSIONS
        ],
    )
    bind.execute(
        sa.insert(
            sa.table(
                "roles",
                sa.column("id"),
                sa.column("key"),
                sa.column("name"),
                sa.column("description"),
                sa.column("scope"),
                sa.column("is_system"),
                sa.column("is_assignable"),
                sa.column("priority"),
                sa.column("created_at"),
                sa.column("updated_at"),
            )
        ),
        [
            {
                "id": _id("role", item.key),
                "key": item.key,
                "name": item.name,
                "description": "",
                "scope": item.scope.value,
                "is_system": True,
                "is_assignable": item.is_assignable,
                "priority": item.priority,
                "created_at": now,
                "updated_at": now,
            }
            for item in SYSTEM_ROLES
        ],
    )
    bind.execute(
        sa.insert(
            sa.table(
                "role_permissions",
                sa.column("role_id"),
                sa.column("permission_id"),
                sa.column("created_at"),
            )
        ),
        [
            {
                "role_id": _id("role", role),
                "permission_id": _id("permission", permission),
                "created_at": now,
            }
            for role, permissions in SYSTEM_ROLE_PERMISSIONS.items()
            for permission in permissions
        ],
    )
    bind.execute(
        sa.insert(
            sa.table(
                "entitlements",
                sa.column("id"),
                sa.column("key"),
                sa.column("name"),
                sa.column("description"),
                sa.column("category"),
                sa.column("is_system"),
                sa.column("created_at"),
                sa.column("updated_at"),
            )
        ),
        [
            {
                "id": _id("entitlement", key),
                "key": key,
                "name": key.replace("_", " ").title(),
                "description": "",
                "category": "platform",
                "is_system": True,
                "created_at": now,
                "updated_at": now,
            }
            for key in ENTITLEMENT_DEFINITIONS
        ],
    )
    bind.execute(
        sa.insert(
            sa.table(
                "feature_flags",
                sa.column("id"),
                sa.column("key"),
                sa.column("name"),
                sa.column("description"),
                sa.column("default_enabled"),
                sa.column("scope"),
                sa.column("created_at"),
                sa.column("updated_at"),
            )
        ),
        [
            {
                "id": _id("feature", key),
                "key": key,
                "name": key.replace("_", " ").title(),
                "description": "",
                "default_enabled": enabled,
                "scope": "global",
                "created_at": now,
                "updated_at": now,
            }
            for key, enabled in FEATURE_DEFINITIONS
        ],
    )
    bind.execute(
        sa.insert(
            sa.table(
                "quota_definitions",
                sa.column("id"),
                sa.column("key"),
                sa.column("name"),
                sa.column("description"),
                sa.column("unit"),
                sa.column("period"),
                sa.column("is_hard_limit"),
                sa.column("created_at"),
                sa.column("updated_at"),
            )
        ),
        [
            {
                "id": _id("quota", key),
                "key": key,
                "name": key.replace(".", " ").title(),
                "description": "",
                "unit": unit,
                "period": period,
                "is_hard_limit": hard,
                "created_at": now,
                "updated_at": now,
            }
            for key, unit, period, hard in QUOTA_DEFINITIONS
        ],
    )
    op.add_column("invitations", sa.Column("organization_role_id", sa.Uuid(), nullable=True))
    op.add_column("invitations", sa.Column("workspace_role_id", sa.Uuid(), nullable=True))
    op.add_column("organization_memberships", sa.Column("role_id", sa.Uuid(), nullable=True))
    op.add_column("workspace_memberships", sa.Column("role_id", sa.Uuid(), nullable=True))
    bind.execute(
        sa.text(
            """UPDATE organization_memberships
            SET role_id = CASE role::text
                WHEN 'owner' THEN CAST(:owner AS uuid)
                WHEN 'admin' THEN CAST(:admin AS uuid) ELSE CAST(:member AS uuid) END"""
        ),
        {
            "owner": _id("role", "organization_owner"),
            "admin": _id("role", "organization_admin"),
            "member": _id("role", "organization_member"),
        },
    )
    bind.execute(
        sa.text(
            """UPDATE workspace_memberships
            SET role_id = CASE role::text
                WHEN 'owner' THEN CAST(:admin AS uuid)
                WHEN 'admin' THEN CAST(:admin AS uuid) ELSE CAST(:viewer AS uuid) END"""
        ),
        {"admin": _id("role", "workspace_admin"), "viewer": _id("role", "viewer")},
    )
    bind.execute(
        sa.text(
            """UPDATE invitations
            SET organization_role_id = CASE organization_role::text
                WHEN 'owner' THEN CAST(:admin AS uuid)
                WHEN 'admin' THEN CAST(:admin AS uuid) ELSE CAST(:member AS uuid) END,
                workspace_role_id = CASE workspace_role::text
                WHEN 'owner' THEN CAST(:workspace_admin AS uuid)
                WHEN 'admin' THEN CAST(:workspace_admin AS uuid)
                ELSE CAST(:viewer AS uuid) END"""
        ),
        {
            "admin": _id("role", "organization_admin"),
            "member": _id("role", "organization_member"),
            "workspace_admin": _id("role", "workspace_admin"),
            "viewer": _id("role", "viewer"),
        },
    )
    op.alter_column("invitations", "organization_role_id", nullable=False)
    op.alter_column("invitations", "workspace_role_id", nullable=False)
    op.alter_column("organization_memberships", "role_id", nullable=False)
    op.alter_column("workspace_memberships", "role_id", nullable=False)
    op.create_foreign_key(
        op.f("fk_invitations_organization_role_id_roles"),
        "invitations",
        "roles",
        ["organization_role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_invitations_workspace_role_id_roles"),
        "invitations",
        "roles",
        ["workspace_role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("invitations", "workspace_role")
    op.drop_column("invitations", "organization_role")
    op.create_index(
        op.f("ix_organization_memberships_role_id"),
        "organization_memberships",
        ["role_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_organization_memberships_role_id_roles"),
        "organization_memberships",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("organization_memberships", "role")
    op.create_index(
        op.f("ix_workspace_memberships_role_id"), "workspace_memberships", ["role_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_workspace_memberships_role_id_roles"),
        "workspace_memberships",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("workspace_memberships", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    membership_role = sa.Enum(
        "owner", "admin", "member", name="vip_membership_role", create_type=False
    )
    op.add_column("workspace_memberships", sa.Column("role", membership_role, nullable=True))
    op.add_column("organization_memberships", sa.Column("role", membership_role, nullable=True))
    op.add_column("invitations", sa.Column("organization_role", membership_role, nullable=True))
    op.add_column("invitations", sa.Column("workspace_role", membership_role, nullable=True))
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """UPDATE organization_memberships m
            SET role = CASE r.key
                WHEN 'organization_owner' THEN 'owner'::vip_membership_role
                WHEN 'organization_admin' THEN 'admin'::vip_membership_role
                ELSE 'member'::vip_membership_role END
            FROM roles r WHERE r.id = m.role_id"""
        )
    )
    bind.execute(
        sa.text(
            """UPDATE workspace_memberships m
            SET role = CASE r.key WHEN 'workspace_admin' THEN 'admin'::vip_membership_role
                ELSE 'member'::vip_membership_role END
            FROM roles r WHERE r.id = m.role_id"""
        )
    )
    bind.execute(
        sa.text(
            """UPDATE invitations i
            SET organization_role = CASE r.key
                WHEN 'organization_admin' THEN 'admin'::vip_membership_role
                ELSE 'member'::vip_membership_role END
            FROM roles r WHERE r.id = i.organization_role_id"""
        )
    )
    bind.execute(
        sa.text(
            """UPDATE invitations i
            SET workspace_role = CASE r.key
                WHEN 'workspace_admin' THEN 'admin'::vip_membership_role
                ELSE 'member'::vip_membership_role END
            FROM roles r WHERE r.id = i.workspace_role_id"""
        )
    )
    for table_name, column_name in [
        ("workspace_memberships", "role"),
        ("organization_memberships", "role"),
        ("invitations", "organization_role"),
        ("invitations", "workspace_role"),
    ]:
        op.alter_column(table_name, column_name, nullable=False)
    op.drop_constraint(
        op.f("fk_workspace_memberships_role_id_roles"), "workspace_memberships", type_="foreignkey"
    )
    op.drop_index(op.f("ix_workspace_memberships_role_id"), table_name="workspace_memberships")
    op.drop_column("workspace_memberships", "role_id")
    op.drop_constraint(
        op.f("fk_organization_memberships_role_id_roles"),
        "organization_memberships",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_organization_memberships_role_id"), table_name="organization_memberships"
    )
    op.drop_column("organization_memberships", "role_id")
    op.drop_constraint(
        op.f("fk_invitations_workspace_role_id_roles"), "invitations", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_invitations_organization_role_id_roles"), "invitations", type_="foreignkey"
    )
    op.drop_column("invitations", "workspace_role_id")
    op.drop_column("invitations", "organization_role_id")
    op.drop_index("ix_quota_usage_tenant", table_name="quota_usage")
    op.drop_table("quota_usage")
    op.drop_index("ix_feature_overrides_tenant", table_name="feature_flag_overrides")
    op.drop_table("feature_flag_overrides")
    op.drop_index("ix_audit_events_workspace_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_type_outcome", table_name="audit_events")
    op.drop_index("ix_audit_events_org_occurred", table_name="audit_events")
    op.drop_index("ix_audit_events_actor", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("organization_quotas")
    op.drop_index("ix_org_entitlements_org_status", table_name="organization_entitlements")
    op.drop_index("ix_org_entitlements_ends_at", table_name="organization_entitlements")
    op.drop_table("organization_entitlements")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_table("quota_definitions")
    op.drop_table("permissions")
    op.drop_table("feature_flags")
    op.drop_table("entitlements")
    # ### end Alembic commands ###
