"""dashboard studio

Revision ID: a069d0a8a1ca
Revises: dbe2b0380363
Create Date: 2026-07-22 13:05:44.813782
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a069d0a8a1ca"
down_revision: str | None = "dbe2b0380363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("default_page_id", sa.Uuid(), nullable=True),
        sa.Column("published_version_id", sa.Uuid(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_dashboards_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_dashboards_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_dashboards_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboards")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_dashboards_tenant_id"
        ),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "slug", name="uq_dashboards_tenant_slug"
        ),
    )
    op.create_index(
        "ix_dashboards_tenant_status",
        "dashboards",
        ["organization_id", "workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "dashboard_filters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("filter_key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("filter_type", sa.String(length=32), nullable=False),
        sa.Column("semantic_model_id", sa.Uuid(), nullable=False),
        sa.Column("dimension_key", sa.String(length=100), nullable=False),
        sa.Column("operator", sa.String(length=32), nullable=False),
        sa.Column("default_value", sa.JSON(), nullable=True),
        sa.Column("widget_ids", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_filters_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_filters")),
        sa.UniqueConstraint("dashboard_id", "filter_key", name="uq_dashboard_filters_key"),
    )
    op.create_table(
        "dashboard_pages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("page_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("canvas", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_pages_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_pages")),
        sa.UniqueConstraint("dashboard_id", "page_key", name="uq_dashboard_pages_key"),
        sa.UniqueConstraint("dashboard_id", "position", name="uq_dashboard_pages_position"),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_dashboard_pages_tenant_id"
        ),
    )
    op.create_table(
        "dashboard_shares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("principal_type", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("permission_level", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_shares_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_shares_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_shares")),
        sa.UniqueConstraint(
            "dashboard_id", "principal_type", "principal_id", name="uq_dashboard_shares_principal"
        ),
    )
    op.create_table(
        "dashboard_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("version_type", sa.String(length=32), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_summary", sa.String(length=500), nullable=False),
        sa.Column("source_version_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_versions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_versions_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["dashboard_versions.id"],
            name=op.f("fk_dashboard_versions_source_version_id_dashboard_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_versions")),
        sa.UniqueConstraint("dashboard_id", "version_number", name="uq_dashboard_versions_number"),
    )
    op.create_index(
        "ix_dashboard_versions_history",
        "dashboard_versions",
        ["dashboard_id", "version_number"],
        unique=False,
    )
    op.create_table(
        "dashboard_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_version_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("filter_state", sa.JSON(), nullable=False),
        sa.Column("data_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_snapshots_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dashboard_version_id"],
            ["dashboard_versions.id"],
            name=op.f("fk_dashboard_snapshots_dashboard_version_id_dashboard_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_snapshots_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_snapshots")),
    )
    op.create_index(
        "ix_dashboard_snapshots_dashboard",
        "dashboard_snapshots",
        ["dashboard_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "dashboard_widgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("dashboard_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("widget_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("semantic_model_id", sa.Uuid(), nullable=True),
        sa.Column("query_definition", sa.JSON(), nullable=False),
        sa.Column("visualization_config", sa.JSON(), nullable=False),
        sa.Column("layout", sa.JSON(), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("interactions", sa.JSON(), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "dashboard_id"],
            ["dashboards.organization_id", "dashboards.workspace_id", "dashboards.id"],
            name="fk_dashboard_widgets_dashboard_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "page_id"],
            [
                "dashboard_pages.organization_id",
                "dashboard_pages.workspace_id",
                "dashboard_pages.id",
            ],
            name="fk_dashboard_widgets_page_tenant",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "workspace_id", "semantic_model_id"],
            [
                "semantic_models.organization_id",
                "semantic_models.workspace_id",
                "semantic_models.id",
            ],
            name="fk_dashboard_widgets_semantic_model_tenant",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_widgets")),
        sa.UniqueConstraint(
            "organization_id", "workspace_id", "id", name="uq_dashboard_widgets_tenant_id"
        ),
    )
    op.create_index(
        "ix_dashboard_widgets_page", "dashboard_widgets", ["dashboard_id", "page_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dashboard_widgets_page", table_name="dashboard_widgets")
    op.drop_table("dashboard_widgets")
    op.drop_index("ix_dashboard_snapshots_dashboard", table_name="dashboard_snapshots")
    op.drop_table("dashboard_snapshots")
    op.drop_index("ix_dashboard_versions_history", table_name="dashboard_versions")
    op.drop_table("dashboard_versions")
    op.drop_table("dashboard_shares")
    op.drop_table("dashboard_pages")
    op.drop_table("dashboard_filters")
    op.drop_index("ix_dashboards_tenant_status", table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
